modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "Polyform-Shield-1.0.0"

[[mods]]
modId = "legacy_tweaks"
version = "${version}"
displayName = "Legacy Tweaks"
authors = "@omo50 (jelly), @LimeGradient"
credits = "@Capeling", "@Permdog99", "@Adrenix", "@WilyIcaro"
description = '''
Brings back many Legacy Console Edition features as configurable tweaks!
'''
#logoFile = ""

[[dependencies.legacy_tweaks]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legacy_tweaks]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.legacy_tweaks]]
modId = "architectury"
type = "required"
versionRange = "[13.0.2,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "legacy_tweaks.mixins.json"
